---
version: 2
multicolumn: false
web-width: 800
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/Residual Block (2)/Residual Block (2).png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/246441/articles/327603/master/file/figures/Residual%20Block%20(2)/Residual%20Block%20(2).png"
    folder_url: "/users/246441/articles/327603/master/folder/figures/Residual Block
      (2)"
